<?php

/**
 * @file
 * Drupal module for React library integration.
 */

/**
 * Implements hook_libraries_info().
 */
function react_libraries_info() {

  $libraries['react'] = [
    'name' => 'react',
    'vendor url' => 'https://facebook.github.io/react/',
    'download url' => 'https://facebook.github.io/react/downloads.html',
    'path' => 'build',
    // The version is in the line 2 of the file. It looks like this currently:
    // * React v0.14.0
    'version arguments' => [
      'file' => 'build/react.min.js',
      'pattern' => '@React v([\d\.]+)@',
      'lines' => 3,
      'cols' => 30,
    ],
    'files' => [
      'js' => [
        'react.min.js',
        'react-dom.min.js',
      ],
    ],
    'variants' => [
      'source' => [
        'files' => [
          'js' => [
            'react.js',
            'react-dom.js',
          ],
        ],
      ],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_library_info_build().
 */
function react_library_info_build() {
  $libraries = [];

  $info = libraries_detect('react');

  if ($info['installed']) {
    $libraries['react'] = [
      'version' => $info['version'],
      'js' => [],
    ];

    if (!empty($info['files']['js'])) {
      foreach ($info['files']['js'] as $data => $option) {
        if (is_numeric($data)) {
          $option = '/' . implode('/', [
            $info['library path'],
            $info['path'],
            $option,
          ]);
        }
        elseif (empty($option['type']) || $option['type'] == 'file') {
          $data = '/' . implode('/', [
            $info['library path'],
            $info['path'],
            $data,
          ]);
        }
        $libraries['react']['js'][$data] = $option;
      }
    }
  }

  return $libraries;
}
